### ISSUE TITLE
Trouble with formats/filenames and downloading resources

### ISSUE THREAD

**Issue by weberdc** [behavioral-ds/BirdSpotter#2] opened 2020-01-28 03:52 UTC
(This was posted as a comment in issue #1 but is reposted here as a new issue.)

Running on a Mac I got this output trying to run birdspotter on a single tweet:

`Thanks for the pointers - I used the rename .full_text to .text trick to get a bit further, but am still having a little trouble, now on a Mac, not just on Windows 10. Can you tell me if this error is related, or should it be a different Issue:

(election) derek@orac ➜ arson ~/Library/Python/3.7/bin/birdspotter -i one_tweet.json -o botscores/overall Starting Tweet Extraction 0it [00:00, ?it/s] Traceback (most recent call last): File "/Users/derek/Library/Python/3.7/bin/birdspotter", line 30, in <module> bs = BirdSpotter(dumpPath, quiet=quiet) File "/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/BirdSpotter.py", line 55, in __init__ self.extractTweets(path, tweetLimit = tweetLimit, embeddings=embeddings) File "/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/BirdSpotter.py", line 241, in extractTweets userDataframe = pd.DataFrame(user_list).fillna(0).set_index('user_id') File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/frame.py", line 4411, in set_index raise KeyError("None of {} are in the columns".format(missing)) KeyError: "None of ['user_id'] are in the columns" (election) derek@orac ➜ arson cat one_tweet.json| jq -rc '.user.id_str' 894082981534384129 (election) derek@orac ➜ arson cat one_tweet.json| jq -rc '.user.id' 894082981534384100 (election) derek@orac ➜ arson cat one_tweet.json| jq -rc '.id_str' 1211893587702497280 (election) derek@orac ➜ arson cat one_tweet.json| jq -rc '.id' 1211893587702497300

I thought I'd try looking at the user id and tweet id fields, and found that the id and id_str values are different, which I didn't expect. I use id_str in all my code, just to ensure I don't get rounding errors, but I'm not sure if it's absolutely necessary - do these results imply it is?

This is all using one tweet, which I'll attach as txt.`

I tried renaming one_tweet.json to one_tweet.jsonl and that got me further:
`(election) derek@orac ➜  arson ~/Library/Python/3.7/bin/birdspotter -i one_tweet.jsonl -o botscores/one_tweet.csv
Starting Tweet Extraction
1it [00:00, 138.51it/s]
Reformatting cascades
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 44.78it/s]
Downloading Fasttext embeddings
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
Getting influence scores of users, with alpha of None, with time decay of -6.8e-05, with beta of 1.0
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 215.57it/s]
`
I also found the output needs to be a file rather than a directory, as I'd expected.

I don't know if all the resources that needed to be downloaded were downloaded, because it ran very quickly (and on Windows, it had spent some time downloading a 2Gb library of some sort for some of the text analysis - wiki-news-300d-1M.vec and <ditto>.vec.zip).

Is it running correctly now, even with the SSL error?
[one_tweet.jsonl.txt](https://github.com/behavioral-ds/BirdSpotter/files/4120549/one_tweet.jsonl.txt)

**Comment by weberdc** [comment] 2020-01-28 03:58
And is this related (running it on a larger dataset now):

`(election) derek@orac ➜  arson ~/Library/Python/3.7/bin/birdspotter -i arson-20191231-20200107_1900-tweaked.jsonl -o botscores/overall/overall.csv
Starting Tweet Extraction
4774it [00:02, 2205.08it/s]
Reformatting cascades
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1164/1164 [00:07<00:00, 165.29it/s]
Downloading Fasttext embeddings
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
Traceback (most recent call last):
  File "/Users/derek/Library/Python/3.7/bin/birdspotter", line 30, in <module>
    bs = BirdSpotter(dumpPath, quiet=quiet)
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/BirdSpotter.py", line 55, in __init__
    self.extractTweets(path,  tweetLimit = tweetLimit, embeddings=embeddings)
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/BirdSpotter.py", line 266, in extractTweets
    self.featureDataframe = self.featureDataframe.join(self.hashtagDataframe)
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/frame.py", line 7261, in join
    other, on=on, how=how, lsuffix=lsuffix, rsuffix=rsuffix, sort=sort
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/frame.py", line 7284, in _join_compat
    sort=sort,
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/reshape/merge.py", line 83, in merge
    return op.get_result()
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/reshape/merge.py", line 648, in get_result
    ldata.items, lsuf, rdata.items, rsuf
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/reshape/merge.py", line 2011, in _items_overlap_with_suffix
    "{rename}".format(rename=to_rename)
ValueError: columns overlap but no suffix specified: Index(['google'], dtype='object')`

**Comment by rohitram96** [comment] 2020-01-28 04:07
@weberdc the word embeddings may have failed to download. The work-around is to download them directly from https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip and unzip them. It might still run with the partial embeddings, but it won't work correctly. 

I'll look into the cause of the SSL issue and get back to you.

**Comment by rohitram96** [comment] 2020-01-28 04:12
@weberdc the second comment has been fixed in the new wheel. It is caused by the overlap between some feature titles and some hashtags used. 

The workaround is to change `self.featureDataframe = self.featureDataframe.join(self.hashtagDataframe)` to `self.featureDataframe = self.featureDataframe.join(self.hashtagDataframe, rsuffix='_hashtag')` inside the `site-packages`, but this is still a temporary fix. A more comprehensive fix will be included in the next release.

**Comment by weberdc** [comment] 2020-01-28 05:23
I got a bit further downloading the zip separately but I'm afraid your beyond my python-fu with the mention of site-packages. This is the output I get with the vec file available in case it's of any use to you:

`(election) derek@orac ➜  arson ~/Library/Python/3.7/bin/birdspotter -i arson-20191231-20200107_1900-tweaked.jsonl -o botscores/overall/overall.csv
Starting Tweet Extraction
4774it [00:02, 1728.51it/s]
Reformatting cascades
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1164/1164 [00:12<00:00, 96.41it/s]
Loading Fasttext wiki-news-300d-1M.vec Word2Vec Embeddings...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 999995/1000000 [01:45<00:00, 9508.45it/s]
Finished loading Word2Vec Embeddings
/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/utils.py:12: FutureWarning: Possible set union at position 66
  punc =  re.findall(r"""[!|"|#|$|%|&|\'|(|)|\*|\+|,|-|.|\/|:|;|<|=|>|\?|@|\[|\\|\]|^|_|`|{|||}|~]""",x)
/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/utils.py:12: FutureWarning: Possible set union at position 67
  punc =  re.findall(r"""[!|"|#|$|%|&|\'|(|)|\*|\+|,|-|.|\/|:|;|<|=|>|\?|@|\[|\\|\]|^|_|`|{|||}|~]""",x)
Traceback (most recent call last):
  File "/Users/derek/Library/Python/3.7/bin/birdspotter", line 30, in <module>
    bs = BirdSpotter(dumpPath, quiet=quiet)
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/BirdSpotter.py", line 55, in __init__
    self.extractTweets(path,  tweetLimit = tweetLimit, embeddings=embeddings)
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/birdspotter/BirdSpotter.py", line 266, in extractTweets
    self.featureDataframe = self.featureDataframe.join(self.hashtagDataframe)
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/frame.py", line 7261, in join
    other, on=on, how=how, lsuffix=lsuffix, rsuffix=rsuffix, sort=sort
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/frame.py", line 7284, in _join_compat
    sort=sort,
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/reshape/merge.py", line 83, in merge
    return op.get_result()
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/reshape/merge.py", line 648, in get_result
    ldata.items, lsuf, rdata.items, rsuf
  File "/Users/derek/Library/Python/3.7/lib/python/site-packages/pandas/core/reshape/merge.py", line 2011, in _items_overlap_with_suffix
    "{rename}".format(rename=to_rename)
ValueError: columns overlap but no suffix specified: Index(['google'], dtype='object')`

Thanks Rohit.

**Comment by rohitram96** [comment] 2020-11-27 01:23
This was caused by a namespace conflict between a hashtag `#google` and the `google` feature. This has been fixed in 2306f98c97324c419c078ccb65369043dbd35073 such that hashtags get a unique namespace.

**Closed by rohitram96** 2020-11-27 01:23 UTC
